import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomUUID, createHash, createHmac, timingSafeEqual, scryptSync } from 'node:crypto';
import { readFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveTxt } from 'node:dns/promises';

const root=dirname(fileURLToPath(import.meta.url));
const encode=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const email=s=>typeof s==='string'&&s.length<=254&&/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(s);
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const equal=(a,b)=>{a=Buffer.from(a||'');b=Buffer.from(b||'');return a.length===b.length&&timingSafeEqual(a,b)};
const text=(v,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const requiredEvents=['email.delivered','email.bounced','email.complained','email.failed'];
export function parseCSV(input){
  input=input.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false;
  for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++}else if(!quoted&&cell!=='')fail('Invalid CSV quote');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c;}
  if(quoted)fail('Unclosed CSV quote');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)fail('CSV is empty');const headers=rows.shift().map(x=>x.trim().toLowerCase());if(!headers.includes('email'))fail('CSV needs an email column');if(new Set(headers).size!==headers.length)fail('CSV contains duplicate headers');return rows.map((r,i)=>{if(r.length!==headers.length)fail('CSV column count mismatch at row '+(i+2));return Object.fromEntries(headers.map((h,j)=>[h,r[j]]))});
}
export function toCSV(rows,headers){const field=x=>{const v=String(x??'');return '"'+(/^[=+@\-\t\r]/.test(v.trimStart())||/^[\t\r]/.test(v)?"'":'')+v.replace(/"/g,'""')+'"'};return '\uFEFF'+[headers.map(field).join(','),...rows.map(r=>headers.map(h=>field(r[h])).join(','))].join('\r\n')}

export function createApp(options={}){
 const cfg={production:process.env.NODE_ENV==='production',password:process.env.ADMIN_PASSWORD||'',appUrl:process.env.APP_URL||process.env.RENDER_EXTERNAL_URL||'http://localhost:3080',database:process.env.DATABASE_PATH||resolve(root,'data/dispatch.sqlite'),unsubscribeSecret:process.env.UNSUBSCRIBE_SECRET||'',apiKey:process.env.RESEND_API_KEY||'',domainId:process.env.RESEND_DOMAIN_ID||'',webhookId:process.env.RESEND_WEBHOOK_ID||'',webhookSecret:process.env.RESEND_WEBHOOK_SECRET||'',allowSend:process.env.ALLOW_SEND==='true',interval:Math.max(750,Number(process.env.SEND_INTERVAL_MS)||750),...options};
 if(cfg.password.length<16)fail('Set ADMIN_PASSWORD to at least 16 characters before starting.');
 const publicURL=new URL(cfg.appUrl);cfg.appUrl=publicURL.origin;
 if(cfg.production&&(publicURL.protocol!=='https:'||cfg.unsubscribeSecret.length<32))fail('Production requires HTTPS APP_URL and a stable UNSUBSCRIBE_SECRET of at least 32 characters.');
 if(cfg.database!==':memory:')mkdirSync(dirname(resolve(cfg.database)),{recursive:true});
 const db=new DatabaseSync(cfg.database);db.exec(`PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1), json TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS contacts(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,company TEXT NOT NULL,status TEXT NOT NULL,consent_source TEXT NOT NULL,consent_at TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS suppressions(email TEXT PRIMARY KEY,reason TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS batches(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',settings TEXT NOT NULL DEFAULT '{}',started_at TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS recipients(batch_id TEXT NOT NULL REFERENCES batches(id),contact_id TEXT NOT NULL REFERENCES contacts(id),status TEXT NOT NULL DEFAULT 'pending',provider_id TEXT,attempts INTEGER NOT NULL DEFAULT 0,first_attempt TEXT,error TEXT,accepted_at TEXT,delivered_at TEXT,opened_at TEXT,clicked_at TEXT,PRIMARY KEY(batch_id,contact_id));
 CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,type TEXT NOT NULL,provider_id TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS event_payloads(id TEXT PRIMARY KEY REFERENCES events(id),json TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS test_emails(id TEXT PRIMARY KEY,fingerprint TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS recipient_provider ON recipients(provider_id);
 `);
 const initial={company:'Ecommerce Gateway Pakistan',website:'https://www.ecgateway.net',address:'',phone:'',accent:'green',user:'Workspace administrator',accountEmail:'',sender:'ECG Marketing',from:'',reply:'',timezone:'Asia/Karachi',provider:'Resend',batch:500,subject:'',preheader:'',message:'',cta:'',ctaUrl:'',unsubscribe:'',footer:'You’re receiving this email because you subscribed to our updates.'};
 db.prepare('INSERT OR IGNORE INTO settings(id,json) VALUES(1,?)').run(JSON.stringify(initial));
 const getSettings=()=>JSON.parse(db.prepare('SELECT json FROM settings WHERE id=1').get().json);
 const fingerprint=s=>createHash('sha256').update(JSON.stringify(s)).digest('hex');
 const contacts=()=>db.prepare('SELECT c.*,s.reason AS suppression_reason,(SELECT COUNT(*) FROM recipients r WHERE r.contact_id=c.id) AS assigned_batches FROM contacts c LEFT JOIN suppressions s ON s.email=c.email ORDER BY c.created_at DESC,c.email').all();
 const members=id=>db.prepare('SELECT c.*,r.*,c.status AS contact_status,s.reason AS suppression_reason FROM recipients r JOIN contacts c ON c.id=r.contact_id LEFT JOIN suppressions s ON s.email=c.email WHERE batch_id=? ORDER BY c.email').all(id);
 const getBatch=id=>{const b=db.prepare('SELECT * FROM batches WHERE id=?').get(id);if(!b)fail('Batch not found',404);return b};
 const eligible=c=>(c.contact_status??c.status)==='subscribed'&&!c.suppression_reason&&!!c.consent_source&&!!c.consent_at;
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}
 function suppress(address,reason){const addr=address.toLowerCase();db.prepare('INSERT OR IGNORE INTO suppressions VALUES(?,?,?)').run(addr,reason,now());db.prepare('UPDATE contacts SET status=? WHERE email=?').run(reason==='unsubscribe'?'unsubscribed':'suppressed',addr)}
 // Correct arity is kept explicit so schema changes do not silently shift fields.
 const insertContact=db.prepare('INSERT INTO contacts(id,email,name,company,status,consent_source,consent_at,created_at) VALUES(?,?,?,?,?,?,?,?)');
 function safeAdd(value){const c={email:text(value.email,254).toLowerCase(),name:text(value.name,100),company:text(value.company,100),status:text(value.status)||'pending',consent_source:text(value.consent_source),consent_at:text(value.consent_at,40)};if(!email(c.email))fail('Invalid email address');if(!['subscribed','pending','unsubscribed','suppressed'].includes(c.status))fail('Invalid contact status');if(c.status==='subscribed'&&(!c.consent_source||!c.consent_at||!Number.isFinite(Date.parse(c.consent_at))||Date.parse(c.consent_at)>Date.now()))fail('Subscribed contacts need a consent source and valid past consent date');if(c.consent_at){if(!Number.isFinite(Date.parse(c.consent_at)))fail('Invalid consent date');c.consent_at=new Date(c.consent_at).toISOString()}if(db.prepare('SELECT id FROM contacts WHERE email=?').get(c.email)){if(['suppressed','unsubscribed'].includes(c.status))suppress(c.email,c.status==='unsubscribed'?'unsubscribe':'manual');return {duplicate:true}};if(db.prepare('SELECT email FROM suppressions WHERE email=?').get(c.email))c.status='suppressed';const id=randomUUID();insertContact.run(id,c.email,c.name,c.company,c.status,c.consent_source,c.consent_at,now());if(['suppressed','unsubscribed'].includes(c.status))suppress(c.email,c.status==='unsubscribed'?'unsubscribe':'manual');return {id}}
 function batchSummary(b){const rows=members(b.id),count=status=>rows.filter(x=>x.status===status).length;return {...b,settings:undefined,total:rows.length,eligible:rows.filter(eligible).length,accepted:rows.filter(x=>x.provider_id).length,delivered:rows.filter(x=>x.delivered_at).length,opened:rows.filter(x=>x.opened_at).length,clicked:rows.filter(x=>x.clicked_at).length,bounced:count('bounced'),complained:count('complained'),failed:count('failed'),unknown:count('unknown'),skipped:count('skipped'),pending:count('pending')+count('sending')};}
 function validation(s){const issues=[];for(const [key,label] of [['company','Company name'],['sender','Sender name'],['address','Physical mailing address'],['subject','Subject'],['message','Message']])if(!text(s[key]))issues.push(label+' is required');if(!email(s.from))issues.push('Valid From email is required');if(!email(s.reply))issues.push('Valid Reply-to email is required');if(/[\r\n<>]/.test(s.sender||''))issues.push('Sender name cannot contain angle brackets or line breaks');if(/[\r\n]/.test(s.subject||''))issues.push('Subject cannot contain line breaks');if(s.provider!=='Resend')issues.push('Only Resend is implemented for this release');if(s.cta&&!/^https:\/\//.test(s.ctaUrl||''))issues.push('CTA requires an HTTPS URL');if(!cfg.apiKey)issues.push('Server RESEND_API_KEY is missing');if(!cfg.domainId)issues.push('Server RESEND_DOMAIN_ID is missing');if(!cfg.webhookId||!cfg.webhookSecret)issues.push('Resend webhook ID and signing secret are required');if(!cfg.unsubscribeSecret)issues.push('Stable UNSUBSCRIBE_SECRET is missing');if(publicURL.protocol!=='https:')issues.push('Deploy with a public HTTPS APP_URL before sending');if(!cfg.allowSend)issues.push('Server ALLOW_SEND is disabled');return issues}
 const fetcher=cfg.fetch||fetch;
 async function provider(path,body,key){const r=await fetcher('https://api.resend.com'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+cfg.apiKey,'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});let value;try{value=await r.json()}catch{value={}}if(!r.ok)throw Object.assign(new Error(text(value.message)||'Provider request failed'),{providerStatus:r.status});return value}
 async function readiness(s,requireTest=true,needed=1){const issues=validation(s);if(!issues.length){try{const domain=await provider('/domains/'+encodeURIComponent(cfg.domainId));if(domain.status!=='verified'||domain.name!==s.from.split('@')[1].toLowerCase()||domain.capabilities?.sending!=='enabled')issues.push('From domain is not verified for sending');for(const record of ['SPF','DKIM'])if(!domain.records?.some(r=>r.record===record&&r.type==='TXT'&&r.status==='verified'))issues.push(record+' record is not verified');const txt=await (cfg.resolveTxt||resolveTxt)('_dmarc.'+domain.name).catch(()=>[]);if(!txt.some(r=>/^v=DMARC1\s*;/i.test(r.join(''))&&/\bp=(none|quarantine|reject)\b/i.test(r.join(''))))issues.push('A valid DMARC DNS record is required');const webhook=await provider('/webhooks/'+encodeURIComponent(cfg.webhookId));if(webhook.status!=='enabled'||webhook.endpoint!==cfg.appUrl+'/webhooks/resend'||requiredEvents.some(e=>!webhook.events?.includes(e)))issues.push('Enable the webhook at APP_URL/webhooks/resend with delivery, bounce, complaint, and failed events');if(webhook.signing_secret&&!equal(webhook.signing_secret,cfg.webhookSecret))issues.push('Webhook signing secret does not match the server configuration');const usage=await provider('/usage');for(const window of ['daily','monthly']){const quota=usage.emails?.[window];if(!quota||!Number.isFinite(quota.used)||(quota.limit!==null&&!Number.isFinite(quota.limit)))issues.push('Could not verify '+window+' sending quota');else if(quota.limit!==null&&quota.limit-quota.used<needed)issues.push('Resend '+window+' quota has only '+Math.max(0,quota.limit-quota.used)+' emails remaining; this send needs '+needed);}}catch(e){issues.push('Provider verification failed: '+e.message)}}if(requireTest&&!db.prepare("SELECT id FROM test_emails WHERE fingerprint=? AND status='delivered'").get(fingerprint(s)))issues.push('Send a test email with these settings and wait for its delivered webhook');return issues}
 function token(addr){return Buffer.from(addr).toString('base64url')+'.'+createHmac('sha256',cfg.unsubscribeSecret).update(addr).digest('base64url')}
 function decodeToken(value){const [data,sig,...rest]=String(value||'').split('.');if(rest.length||!data||!sig||!cfg.unsubscribeSecret)fail('Invalid unsubscribe link',400);const addr=Buffer.from(data,'base64url').toString();if(!email(addr)||!equal(sig,createHmac('sha256',cfg.unsubscribeSecret).update(addr).digest('base64url')))fail('Invalid unsubscribe link',400);return addr}
 function payload(s,addr){const unsubscribe=cfg.appUrl+'/unsubscribe?token='+encodeURIComponent(token(addr));return {from:s.sender+' <'+s.from+'>',to:[addr],reply_to:s.reply,subject:s.subject,text:[s.preheader,s.message,s.cta?s.cta+': '+s.ctaUrl:'',s.company,s.address,s.footer,'Unsubscribe: '+unsubscribe].filter(Boolean).join('\n\n'),html:`<!doctype html><html lang="en"><head><title>${encode(s.subject)}</title></head><body style="margin:0;background:#f4f6f1;font-family:Arial,sans-serif;color:#25301e"><div style="max-width:600px;margin:24px auto;background:white;padding:32px"><div style="display:none;max-height:0;overflow:hidden">${encode(s.preheader)}</div><h1 style="font-size:24px">${encode(s.subject)}</h1><p style="font-size:16px;line-height:1.7;white-space:pre-line">${encode(s.message)}</p>${s.cta?`<p><a style="display:inline-block;padding:14px 20px;background:#c2ed83;color:#25301e" href="${encode(s.ctaUrl)}">${encode(s.cta)}</a></p>`:''}<hr><p style="font-size:12px;line-height:1.7">${encode(s.company)}<br>${encode(s.address)}<br>${encode(s.footer)}<br><a href="${encode(unsubscribe)}">Unsubscribe</a></p></div></body></html>`,headers:{'List-Unsubscribe':'<'+unsubscribe+'>','List-Unsubscribe-Post':'List-Unsubscribe=One-Click'}}}
 let working=false,closed=false;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 async function worker(){if(working||closed)return;working=true;try{for(;;){const batch=db.prepare("SELECT * FROM batches WHERE status='sending' ORDER BY created_at LIMIT 1").get();if(!batch)break;const s=JSON.parse(batch.settings);let stopped=false;for(const r of members(batch.id).filter(r=>['pending','sending'].includes(r.status))){if(closed)break;if(getBatch(batch.id).status!=='sending'){stopped=true;break}const live=db.prepare('SELECT c.*,s.reason AS suppression_reason FROM contacts c LEFT JOIN suppressions s ON s.email=c.email WHERE c.id=?').get(r.contact_id);if(!eligible(live)){db.prepare("UPDATE recipients SET status='skipped',error='No longer eligible' WHERE batch_id=? AND contact_id=?").run(batch.id,r.contact_id);continue}if(r.first_attempt&&Date.now()-Date.parse(r.first_attempt)>23*3600000){db.prepare("UPDATE recipients SET status='unknown',error='Idempotency window expired; reconcile in Resend before any resend' WHERE batch_id=? AND contact_id=?").run(batch.id,r.contact_id);continue}if(!cfg.allowSend||!cfg.apiKey){db.prepare("UPDATE batches SET status='paused' WHERE id=?").run(batch.id);stopped=true;break}db.prepare("UPDATE recipients SET status='sending',attempts=attempts+1,first_attempt=COALESCE(first_attempt,?) WHERE batch_id=? AND contact_id=?").run(now(),batch.id,r.contact_id);try{const result=await provider('/emails',payload(s,live.email),'dispatch-'+batch.id+'-'+r.contact_id);if(!result.id)throw new Error('Provider returned no message ID');db.prepare("UPDATE recipients SET status='accepted',provider_id=?,accepted_at=?,error=NULL WHERE batch_id=? AND contact_id=?").run(result.id,now(),batch.id,r.contact_id);transaction(()=>replayEvents(result.id));}catch(e){const uncertain=!e.providerStatus||e.providerStatus>=500||e.providerStatus===429;if(uncertain){db.prepare("UPDATE recipients SET error=? WHERE batch_id=? AND contact_id=?").run(text(e.message),batch.id,r.contact_id);db.prepare("UPDATE batches SET status='paused' WHERE id=?").run(batch.id);stopped=true;break}else{db.prepare("UPDATE recipients SET status='failed',error=? WHERE batch_id=? AND contact_id=?").run(text(e.message),batch.id,r.contact_id);if([401,403,402].includes(e.providerStatus)){db.prepare("UPDATE batches SET status='paused' WHERE id=?").run(batch.id);stopped=true;break}}}await sleep(cfg.interval);}
 if(!stopped&&!closed)db.prepare("UPDATE batches SET status='completed' WHERE id=? AND status='sending'").run(batch.id);if(closed)break;}}catch(e){console.error('Send worker stopped:',e.message)}finally{working=false}}
 const sessions=new Map(),loginAttempts=new Map(),salt=randomBytes(16),passwordHash=scryptSync(cfg.password,salt,32);
 async function rawBody(req){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>5*1024*1024)fail('Request too large',413);chunks.push(c)}return Buffer.concat(chunks).toString('utf8')}
 const json=(res,value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value))};
 const html=(res,value,status=200)=>{res.writeHead(status,{'Content-Type':'text/html; charset=utf-8'});res.end(value)};
 const download=(res,value,name)=>{res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${name}"`});res.end(value)};
 function auth(req){const cookie=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('dispatch_session='))?.slice(17),session=sessions.get(cookie);if(!session||session.expires<Date.now()){if(cookie)sessions.delete(cookie);fail('Sign in to continue',401)}return session}
 function verifyWebhook(req,body){const id=req.headers['svix-id'],timestamp=req.headers['svix-timestamp'],signature=req.headers['svix-signature'];if(!cfg.webhookSecret||!id||!timestamp||!signature||!/^\d+$/.test(timestamp)||Math.abs(Date.now()/1000-Number(timestamp))>300)fail('Invalid webhook signature',401);const secret=Buffer.from(cfg.webhookSecret.replace(/^whsec_/,''),'base64');const expected=createHmac('sha256',secret).update(id+'.'+timestamp+'.'+body).digest('base64');if(!signature.split(' ').some(s=>s.startsWith('v1,')&&equal(s.slice(3),expected)))fail('Invalid webhook signature',401);return id}
 function applyEvent(event){const r=db.prepare('SELECT * FROM recipients WHERE provider_id=?').get(event.data.email_id);if(event.type==='email.delivered'){db.prepare("UPDATE test_emails SET status='delivered' WHERE id=? AND status='accepted'").run(event.data.email_id);db.prepare("UPDATE recipients SET delivered_at=COALESCE(delivered_at,?),status=CASE WHEN status IN ('bounced','complained','failed') THEN status ELSE 'delivered' END WHERE provider_id=?").run(now(),event.data.email_id)}if(event.type==='email.opened')db.prepare('UPDATE recipients SET opened_at=COALESCE(opened_at,?) WHERE provider_id=?').run(now(),event.data.email_id);if(event.type==='email.clicked')db.prepare('UPDATE recipients SET clicked_at=COALESCE(clicked_at,?) WHERE provider_id=?').run(now(),event.data.email_id);if(['email.bounced','email.complained','email.failed'].includes(event.type)){const status=event.type.split('.')[1];db.prepare('UPDATE recipients SET status=?,error=? WHERE provider_id=?').run(status,text(event.data.bounce?.message||event.data.failed?.reason||status),event.data.email_id);db.prepare('UPDATE test_emails SET status=? WHERE id=?').run(status,event.data.email_id);if(status==='bounced'||status==='complained'){for(const address of event.data.to||[])if(email(address))suppress(address,status);if(r){const contact=db.prepare('SELECT email FROM contacts WHERE id=?').get(r.contact_id);suppress(contact.email,status)}}}if(r&&['email.bounced','email.complained'].includes(event.type)){const summary=batchSummary(getBatch(r.batch_id));if(summary.complained>0||summary.bounced>=Math.max(1,Math.ceil(summary.total*0.02)))db.prepare("UPDATE batches SET status='paused' WHERE id=? AND status='sending'").run(r.batch_id)}}
 function replayEvents(providerId){for(const row of db.prepare('SELECT p.json FROM event_payloads p JOIN events e ON e.id=p.id WHERE e.provider_id=? ORDER BY e.created_at,e.rowid').all(providerId))applyEvent(JSON.parse(row.json))}
 async function handler(req,res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");if(cfg.production)res.setHeader('Strict-Transport-Security','max-age=31536000');try{const url=new URL(req.url,'http://localhost'),path=url.pathname,method=req.method;
 if(path==='/health'){res.writeHead(200);return res.end('ok')}
 if(path==='/unsubscribe'&&['GET','POST'].includes(method)){const addr=decodeToken(url.searchParams.get('token'));if(method==='POST'){suppress(addr,'unsubscribe');return html(res,'<html lang="en"><meta name="viewport" content="width=device-width"><title>Unsubscribed</title><h1>You have been unsubscribed.</h1><p>You will no longer receive marketing emails from this workspace.</p></html>')}return html(res,`<html lang="en"><meta name="viewport" content="width=device-width"><title>Unsubscribe</title><h1>Unsubscribe from marketing emails</h1><p>Confirm below. You do not need an account.</p><form method="post"><button style="padding:16px">Unsubscribe</button></form></html>`)}
 if(path==='/webhooks/resend'&&method==='POST'){const raw=await rawBody(req),eventId=verifyWebhook(req,raw);let event;try{event=JSON.parse(raw)}catch{fail('Invalid webhook JSON')}if(!event.data?.email_id||!event.type)fail('Invalid event');transaction(()=>{if(db.prepare('SELECT id FROM events WHERE id=?').get(eventId))return;db.prepare('INSERT INTO events VALUES(?,?,?,?)').run(eventId,event.type,event.data.email_id,now());db.prepare('INSERT INTO event_payloads(id,json) VALUES(?,?)').run(eventId,raw);applyEvent(event);});return json(res,{received:true})}
 if(path==='/api/login'&&method==='POST'){if(req.headers.origin&&req.headers.origin!==cfg.appUrl)fail('Invalid request origin',403);const ip=req.socket.remoteAddress,t=loginAttempts.get(ip)||{count:0,start:Date.now()};if(Date.now()-t.start>900000){t.count=0;t.start=Date.now()}if(t.count>=10)fail('Too many sign-in attempts; wait 15 minutes',429);t.count++;loginAttempts.set(ip,t);const value=JSON.parse(await rawBody(req));if(typeof value.password!=='string'||value.password.length>200||!equal(scryptSync(value.password,salt,32),passwordHash))fail('Incorrect password',401);loginAttempts.delete(ip);const sid=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(sid,{csrf,expires:Date.now()+8*3600000});res.setHeader('Set-Cookie',`dispatch_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${cfg.production?'; Secure':''}`);return json(res,{csrf})}
 if(path.startsWith('/api/')){const session=auth(req);if(!['GET','HEAD'].includes(method)&&(!equal(req.headers['x-csrf-token'],session.csrf)||(req.headers.origin&&req.headers.origin!==cfg.appUrl)))fail('Invalid request origin or CSRF token',403);const value=async()=>{try{return JSON.parse(await rawBody(req))}catch(e){if(e.status)throw e;fail('Invalid JSON')}};
 if(path==='/api/session'&&method==='GET')return json(res,{csrf:session.csrf});
 if(path==='/api/logout'&&method==='POST'){for(const [key,s]of sessions)if(s===session)sessions.delete(key);res.setHeader('Set-Cookie','dispatch_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,{ok:true})}
 if(path==='/api/state'&&method==='GET')return json(res,{settings:getSettings(),contacts:contacts(),batches:db.prepare('SELECT * FROM batches ORDER BY created_at DESC').all().map(batchSummary),provider:{name:'Resend',keyConfigured:!!cfg.apiKey,domainConfigured:!!cfg.domainId,webhookConfigured:!!cfg.webhookId&&!!cfg.webhookSecret,allowSend:cfg.allowSend,publicUrl:cfg.appUrl},tests:db.prepare('SELECT * FROM test_emails ORDER BY created_at DESC LIMIT 10').all()});
 if(path==='/api/settings'&&method==='PUT'){const input=await value(),s={};for(const k of Object.keys(initial))s[k]=text(String(input[k]??''),k==='message'?10000:k==='address'?1000:500);s.batch=Number(input.batch);if(!Number.isInteger(s.batch)||s.batch<1||s.batch>500)fail('Batch size must be 1–500');try{new Intl.DateTimeFormat('en',{timeZone:s.timezone})}catch{fail('Invalid timezone')}for(const k of ['website','ctaUrl'])if(s[k]){let u;try{u=new URL(s[k])}catch{fail('Invalid '+k+' URL')}if(!['https:','http:'].includes(u.protocol))fail('Invalid '+k+' URL scheme')}db.prepare('UPDATE settings SET json=? WHERE id=1').run(JSON.stringify(s));return json(res,{ok:true})}
 if(path==='/api/contacts'&&method==='POST'){const input=await value(),result=transaction(()=>safeAdd(input));return json(res,result,result.duplicate?200:201)}
 if(path==='/api/contacts/import'&&method==='POST'){const input=await value(),rows=parseCSV(String(input.csv||''));if(rows.length>20000)fail('Import at most 20,000 rows at a time');let added=0,duplicates=0,errors=[];transaction(()=>rows.forEach((r,i)=>{try{const result=safeAdd(r);result.duplicate?duplicates++:added++}catch(e){if(errors.length<100)errors.push({row:i+2,email:text(r.email),error:e.message})}}));return json(res,{added,duplicates,invalid:rows.length-added-duplicates,errors})}
 if(path==='/api/contacts/export'&&method==='GET'){const ids=url.searchParams.get('ids')?.split(','),rows=contacts().filter(c=>!ids||ids.includes(c.id));return download(res,toCSV(rows,['email','name','company','status','consent_source','consent_at','created_at','suppression_reason']),'contacts.csv')}
 const contactMatch=path.match(/^\/api\/contacts\/([^/]+)$/);if(contactMatch&&method==='PATCH'){const c=db.prepare('SELECT * FROM contacts WHERE id=?').get(contactMatch[1]);if(!c)fail('Contact not found',404);const input=await value();if(!['unsubscribed','suppressed'].includes(input.status))fail('Only unsubscribe or suppression changes are supported. Reactivation needs a separate verified opt-in workflow.');suppress(c.email,input.status==='unsubscribed'?'unsubscribe':'manual');return json(res,{ok:true})}
 if(path==='/api/batches'&&method==='POST'){const input=await value(),name=text(input.name,100),ids=[...new Set(input.contactIds||[])];if(!name||!ids.length||ids.length>500)fail('Give the list a name and select 1–500 contacts');const id=randomUUID();transaction(()=>{for(const cid of ids){const c=db.prepare('SELECT c.*,s.reason AS suppression_reason FROM contacts c LEFT JOIN suppressions s ON s.email=c.email WHERE c.id=?').get(cid);if(!c||!eligible(c))fail('All selected contacts must have documented consent and no suppression')}db.prepare('INSERT INTO batches(id,name,status,created_at) VALUES(?,?,?,?)').run(id,name,'draft',now());const insert=db.prepare('INSERT INTO recipients(batch_id,contact_id) VALUES(?,?)');ids.forEach(cid=>insert.run(id,cid))});return json(res,{id},201)}
 const bm=path.match(/^\/api\/batches\/([^/]+)(?:\/(review|send|pause|resume|report))?$/);if(bm){const b=getBatch(bm[1]),action=bm[2];if(!action&&method==='GET')return json(res,{batch:batchSummary(b),recipients:members(b.id)});if(action==='report'&&method==='GET')return download(res,toCSV(members(b.id),['email','name','status','provider_id','attempts','error','accepted_at','delivered_at','opened_at','clicked_at']),'batch-'+b.id+'.csv');if(action==='review'&&method==='GET'){const s=getSettings(),rows=members(b.id),issues=await readiness(s,true,rows.length);if(rows.some(c=>!eligible(c)))issues.push('Some saved recipients are no longer eligible');if(b.status!=='draft')issues.push('This batch has already started');const reviewToken=createHmac('sha256',passwordHash).update(b.id+fingerprint(s)+JSON.stringify(rows.map(r=>[r.contact_id,r.status,r.suppression_reason]))).digest('hex');return json(res,{batch:batchSummary(b),issues,reviewToken,settings:s})}if(action==='send'&&method==='POST'){const input=await value();if(b.status!=='draft')fail('This batch has already started',409);const s=getSettings(),rows=members(b.id),issues=await readiness(s,true,rows.length);if(rows.some(c=>!eligible(c)))issues.push('A recipient is no longer eligible');const expected=createHmac('sha256',passwordHash).update(b.id+fingerprint(s)+JSON.stringify(rows.map(r=>[r.contact_id,r.status,r.suppression_reason]))).digest('hex');if(!equal(input.reviewToken,expected)||input.confirmation!=='SEND '+rows.length)fail('Review changed or confirmation does not match',409);if(issues.length)fail(issues.join('; '),409);const updated=db.prepare("UPDATE batches SET status='sending',settings=?,started_at=? WHERE id=? AND status='draft'").run(JSON.stringify(s),now(),b.id);if(!updated.changes)fail('Batch already started',409);json(res,{ok:true},202);void worker();return}if(action==='pause'&&method==='POST'){db.prepare("UPDATE batches SET status='paused' WHERE id=? AND status='sending'").run(b.id);return json(res,{ok:true})}if(action==='resume'&&method==='POST'){if(b.status!=='paused')fail('Only paused batches can resume');const issues=await readiness(JSON.parse(b.settings),true,members(b.id).filter(r=>['pending','sending'].includes(r.status)).length);if(issues.length)fail(issues.join('; '),409);db.prepare("UPDATE batches SET status='sending' WHERE id=? AND status='paused'").run(b.id);json(res,{ok:true},202);void worker();return}}
 if(path==='/api/test-email'&&method==='POST'){const input=await value(),s=getSettings();if(!email(input.email))fail('Enter a valid test email address');const issues=await readiness(s,false);if(issues.length)fail(issues.join('; '),409);if(db.prepare('SELECT email FROM suppressions WHERE email=?').get(input.email.toLowerCase()))fail('This test address is suppressed');const result=await provider('/emails',payload(s,input.email.toLowerCase()),'test-'+randomUUID());if(!result.id)fail('Provider returned no email ID',502);db.prepare('INSERT INTO test_emails VALUES(?,?,?,?)').run(result.id,fingerprint(s),'accepted',now());transaction(()=>replayEvents(result.id));return json(res,{id:result.id},202)}
 if(path==='/api/readiness'&&method==='GET')return json(res,{issues:await readiness(getSettings()),unsubscribeEndpoint:cfg.appUrl+'/unsubscribe'});
 fail('API route not found',404)}
 if(method==='GET'&&(path==='/'||path==='/email-marketing.html')){let source=readFileSync(resolve(root,'../email-marketing.html'),'utf8');source=source.replace('</head>','<style>main{visibility:hidden}</style></head>').replace('</body>','<script src="/production.js"></script></body>');return html(res,source)}
 if(method==='GET'&&path==='/production.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8'});return res.end(readFileSync(resolve(root,'production.js')))}fail('Not found',404)
 }catch(e){json(res,{error:e.status?e.message:'Request failed. Check server logs.'},e.status||500);if(!e.status)console.error(e.message)}}
 const server=http.createServer(handler);return {server,db,cfg,worker,close:async()=>{closed=true;while(working)await sleep(25);await new Promise(r=>server.close(r));db.close()}};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const app=createApp();const host=process.env.NODE_ENV==='production'?(process.env.HOST||'0.0.0.0'):'127.0.0.1';app.server.listen(Number(process.env.PORT)||3080,host,()=>{console.log('Dispatch running at '+app.cfg.appUrl+' · live sending '+(app.cfg.allowSend?'enabled':'disabled'));void app.worker()});for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>void app.close().then(()=>process.exit(0)))}
